name: broken action

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: .

jobs:
  say-working:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: echo "this workflow runs correctly"
      - uses: ./.github/simple-composite-action
      - name: check out other branch
        run: |
          git branch
          git checkout no-composite-action
